#!/usr/bin/env bash
# PostToolUse hook: warn when a Write or Edit touches a generated file.
# Reads the tool input JSON from stdin and checks the file path.
# Exits 0 (non-blocking) in all cases — this is advisory, not a hard block.

set -euo pipefail

input=$(cat)

# Extract the file path from the tool input (works for both Write and Edit)
file_path=$(printf '%s' "$input" | python3 -c "
import sys, json
data = json.load(sys.stdin)
inp = data.get('tool_input', {})
print(inp.get('file_path', inp.get('path', '')))
" 2>/dev/null || true)

if [ -z "$file_path" ]; then
    exit 0
fi

basename=$(basename "$file_path")

# Check by filename pattern
is_generated=false
case "$basename" in
    zz_generated.*.go|zz_generated.go)
        is_generated=true
        ;;
esac

# Also check file contents for the "Code generated" header (if file exists)
if [ "$is_generated" = false ] && [ -f "$file_path" ]; then
    if head -5 "$file_path" 2>/dev/null | grep -q "Code generated"; then
        is_generated=true
    fi
fi

if [ "$is_generated" = true ]; then
    msg="WARNING: '$basename' appears to be a generated file (contains 'Code generated' header or matches zz_generated.* pattern). Do NOT edit this file manually. Run 'make generate' instead and commit the output in a separate commit."
    printf '{"additionalContext": "%s"}\n' "$msg"
fi

exit 0
