#!/usr/bin/env bash
# PreToolUse hook: block edits to generated files.
# Generated files must only be produced by `cd api && make generate` — never manually edited.
# This hook fires BEFORE the Edit/Write tool executes and can block the operation.

set -euo pipefail

TOOL_NAME="${CLAUDE_TOOL_NAME:-}"
FILE_PATH="${CLAUDE_TOOL_INPUT_file_path:-${CLAUDE_TOOL_INPUT_filePath:-}}"

if [[ "$TOOL_NAME" != "Edit" && "$TOOL_NAME" != "Write" ]]; then
    exit 0
fi

if [ -z "$FILE_PATH" ]; then
    exit 0
fi

# Normalise to basename checks and pattern matches
BASENAME=$(basename "$FILE_PATH")

blocked=false
reason=""

# 1. DeepCopy generated files
if [[ "$BASENAME" == zz_generated* ]]; then
    blocked=true
    reason="zz_generated files are produced by controller-gen via 'cd api && make generate'. Never edit manually."
fi

# 2. CRD YAML files under api/core/v1alpha1/crds/ or charts/crds/
if [[ "$FILE_PATH" == */api/core/v1alpha1/crds/*.yaml ]] || \
   [[ "$FILE_PATH" == */api/core/v1alpha1/crds/*.yml ]]; then
    blocked=true
    reason="CRD YAML files under api/core/v1alpha1/crds/ are generated by 'cd api && make generate'. Never edit manually."
fi

if [[ "$FILE_PATH" == */charts/crds/*.yaml ]] || \
   [[ "$FILE_PATH" == */charts/crds/*.yml ]]; then
    blocked=true
    reason="CRD YAML files under charts/crds/ are copied from generated CRDs by 'cd api && make generate'. Never edit manually."
fi

# 3. Generated client library
if [[ "$FILE_PATH" == */client/clientset/* ]] || \
   [[ "$FILE_PATH" == */client/informers/* ]] || \
   [[ "$FILE_PATH" == */client/listers/* ]]; then
    blocked=true
    reason="The client/ directory contains generated clientset, informers, and listers. Run 'cd api && make generate' instead."
fi

# 4. Generated API reference docs
if [[ "$BASENAME" == "etcd-druid-api.md" ]] && [[ "$FILE_PATH" == */docs/api-reference/* ]]; then
    blocked=true
    reason="docs/api-reference/etcd-druid-api.md is generated by 'cd api && make generate-api-docs'. Never edit manually."
fi

if [ "$blocked" = true ]; then
    cat <<EOF
{
  "decision": "block",
  "reason": "BLOCKED: This is a generated file. ${reason} To regenerate: cd api && make generate"
}
EOF
    exit 0
fi

# Not a generated file — allow the edit
exit 0
